config/routes.rb
Rails.application.routes.draw do
  resources :products

  devise_for :users

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, presence: true
	validates :description, presence: true
	validates :price, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # before_action :authenticate_user!

  def new
    @product = Product.new
  end

  def index
    @products =Product.all
  end

  def create
    #render plain: params[:product].inspect
    @product = Product.new(product_param) 

    if @product.save
      flash[:notice] = "the product  was succesfully saved"
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def show
    @product = Product.find(params[:id])
  end

  def update
    @product = @product = Product.find(params[:id])
    if @product.update(product_param)
      redirect_to product_path(@product)

    else
      
      render 'edit'

    end
        
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      redirect_to products_path
    end
  end

  private

  def product_param
  params.require(:product).permit(:name,:description,:price)    

  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/layouts/fluid.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Exam" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Exam</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/products/create.html.erb
<h1>Product#create</h1>
<p>Find me in app/views/product/create.html.erb</p>

app/views/products/delate.html.erb
<h1>Product#delate</h1>
<p>Find me in app/views/product/delate.html.erb</p>

app/views/products/edit.html.erb
<h1> creating new form </h1> 

<% if @product.errors.any? %>
<ul><% @product.errors.full_messages.each do |msg| %>
	<li><%= msg %> </li>
	<% end %> 
</ul>
<%end %>
	
end
<table>

<%= form_for @product do |p| %>
	<p>
	<%= p.label :name %></br>
	<%= p.text_field :name %>
	</p>

	<p>
	<%= p.label :description %></br>
	<%= p.text_area :description %>
 	</p>

 	<p>
	<%= p.label :price  %></br>
	<%= p.text_field :price %>
	</p>

	<p>
 	<%= p.submit %>
 	</p>
 <% end %>
</table>

app/views/products/index.html.erb
<table>
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th>Price</th>
	</tr>

	<% @products.each do |p| %>
	<tr>
		<td> <%= p.name %></td>
		<td> <%= p.description %></td>
		<td> <%= p.price %> </td>
		<td> <%=link_to "edit",edit_product_path(p) %></td>
		<td> <%=link_to "show",product_path(p) %> </td>
		<td> <%=link_to "delete",product_path(p), method: :delete %> </td>
	</tr>
	<% end %>
</table>

app/views/products/new.html.erb
<h1> creating new form </h1> 
<table>

<%= form_for @product do |p| %>
	<p>
	<%= p.label :name %></br>
	<%= p.text_field :name %>
	</p>

	<p>
	<%= p.label :description %></br>
	<%= p.text_area :description %>
 	</p>

 	<p>
	<%= p.label :price  %></br>
	<%= p.text_field :price %>
	</p>

	<p>
 	<%= p.submit %>
 	</p>
 <% end %>
</table>

app/views/products/show.html.erb
<h2> Show records</h5>

<h3>name: <%=@product.name %> </h3>
<h3>description: <%=@product.description %> </h3>
<h3>price:<%=@product.price %></h3>
<%=link_to "back",products_path %>

app/views/products/update.html.erb
<h1>Product#update</h1>
<p>Find me in app/views/product/update.html.erb</p>